name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: fetch dependancy
      run: apt install libxml2-dev
    
    - name: Setup
      run: mkdir bin
    
    - name: Make it.
      run: make
